#!/bin/sh
export "CFLAGS=-ftest-coverage -fprofile-arcs"
# force recompilation
rm -fR ./build/temp.linux-i686-2.4/source/*.o
rm -fR ./build/lib.linux-i686-2.4/*.so
python setup.py testlocal
gcov source/*.c -o ./build/temp.linux-i686-2.4/source/
# look for lines with the gcov marker #####, but exclude those where the line ends with /*COV*/
#
# Does anyone know how I can use grep to atch lines that include '#####' but NOT include '/*COV*/' ?
#
# I should probably better write a Python script...
#
grep -c "#####.*[^C][^O][^V][^*][^/]$" *.c.gcov
echo "TOTAL:"
cat *.c.gcov | grep -c "#####.*[^C][^O][^V][^*][^/]$"