#!/bin/sh
cat <<EOF
This script can be used to extract libffi from a gcc cvs checkout.

To run it, let GCCSRC (see below) point to the top directory of the
gcc checkout, and start it with ctypes/source as current working
directory.

But beware, the directory tree ctypes/source/gcc will be replaced and
the CVS directories will be lost. This is normally not what you want!

Instead, you can rename the CVS.gcc directories with the script
cvs-switch (CVS -> CVS.ctypes, CVS.gcc -> CVS), do an update from the
gcc cvs repository, and run cvs-switch again (which reverses the
rename operation).
EOF
exit
GCCSRC=$HOME/cvs/gcc # XXX: change this
ADOPTFILES="ltmain.sh ltconfig install-sh config.sub config.guess \
	missing ltcf-c.sh gcc/version.c config-ml.in depcomp"

rm -rf gcc
mkdir -p gcc/gcc/testsuite
cp -Rp $GCCSRC/libffi gcc
cp -Rp $GCCSRC/gcc/testsuite/lib gcc/gcc/testsuite
find gcc -name CVS | xargs -i mv {} {}.gcc
for f in $ADOPTFILES; do
	cp -pf $GCCSRC/$f gcc/libffi
done
# we don't want multiple targets
sed -i -e 's,\.\./gcc/version\.c,version.c,g' \
	-e 's,^\( *multi_basedir=\)"[^"]*",\1"\$srcdir",g' \
	gcc/libffi/configure
# we don't paths with target and gcc version embedded
sed -i -e '/^gcc_version *:=/d' \
	-e '/^toollibffidir *:=/s,/\$(target_alias)/\$(gcc_version),,' \
	gcc/libffi/include/Makefile.am gcc/libffi/include/Makefile.in
# hack libffi-dg.exp to get the testsuite going
sed -i -e '/ *set blddirffi /s,.*,set blddirffi "${objdir}/..",' \
	gcc/libffi/testsuite/lib/libffi-dg.exp
# old OS X build utilities do not know the section attribut live_support.
# Add an option to hide it.
patch --no-backup -s -p0 <<EOF
--- gcc/libffi/src/powerpc/darwin_closure.S.old  Thu Mar 24 01:45:38 2005
+++ gcc/libffi/src/powerpc/darwin_closure.S  Sat May 14 03:25:47 2005
@@ -246,7 +246,11 @@
 /* END(ffi_closure_ASM)  */

 .data
+#ifdef no_live_support
+.section __TEXT,__eh_frame,coalesced,no_toc+strip_static_syms
+#else
 .section __TEXT,__eh_frame,coalesced,no_toc+strip_static_syms+live_support
+#endif
 EH_frame1:
        .set    L$set$0,LECIE1-LSCIE1
        .long   L$set$0 ; Length of Common Information Entry
EOF
