#!/bin/sh
set -e
MV="mv"
cd "$(dirname "$0")"/../source/gcc
if [ -e libffi/CVS.gcc ]; then
  for f in $(find . -name CVS | sort -r); do
    [ -e "$f".ctypes ] && continue
    $MV "$f" "$f".ctypes
    [ -e "$f".gcc ] && $MV "$f".gcc "$f"
  done
  echo 'now using gcc repository'
else
  for f in $(find . -name CVS.ctypes | sort -r); do
    f="$(dirname "$f")/$(basename "$f" .ctypes)"
    [ -e "$f" ] && $MV "$f" "$f".gcc
    $MV "$f".ctypes "$f"
  done
  echo 'now using ctypes repository'
fi
